'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\DLs\IMDB\Compressed")>  _
        Public Property FolderLocation() As String
            Get
                Return CType(Me("FolderLocation"),String)
            End Get
            Set
                Me("FolderLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsd=""http://www.w3."& _ 
            "org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>https://datasets.imdbws.com/name.basics.tsv.gz</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>https:/"& _ 
            "/datasets.imdbws.com/title.akas.tsv.gz</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>https://datasets.imdb"& _ 
            "ws.com/title.basics.tsv.gz</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>https://datasets.imdbws.com/title"& _ 
            ".crew.tsv.gz</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>https://datasets.imdbws.com/title.episode.tsv.g"& _ 
            "z</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>https://datasets.imdbws.com/title.principals.tsv.gz</strin"& _ 
            "g>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>https://datasets.imdbws.com/title.ratings.tsv.gz</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</Array"& _ 
            "OfString>")>  _
        Public Property ArchiveList() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ArchiveList"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ArchiveList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property OverallSavedStartTime() As Date
            Get
                Return CType(Me("OverallSavedStartTime"),Date)
            End Get
            Set
                Me("OverallSavedStartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NameBasicsSavedStartTime() As Date
            Get
                Return CType(Me("NameBasicsSavedStartTime"),Date)
            End Get
            Set
                Me("NameBasicsSavedStartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleAkasSavedStartTime() As Date
            Get
                Return CType(Me("TitleAkasSavedStartTime"),Date)
            End Get
            Set
                Me("TitleAkasSavedStartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleBasicsSavedStartTime() As Date
            Get
                Return CType(Me("TitleBasicsSavedStartTime"),Date)
            End Get
            Set
                Me("TitleBasicsSavedStartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleCrewSavedStartTime() As Date
            Get
                Return CType(Me("TitleCrewSavedStartTime"),Date)
            End Get
            Set
                Me("TitleCrewSavedStartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleEpisodeSavedStartTime() As Date
            Get
                Return CType(Me("TitleEpisodeSavedStartTime"),Date)
            End Get
            Set
                Me("TitleEpisodeSavedStartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitlePrincipalsSavedStartTime() As Date
            Get
                Return CType(Me("TitlePrincipalsSavedStartTime"),Date)
            End Get
            Set
                Me("TitlePrincipalsSavedStartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleRatingsSavedStartTime() As Date
            Get
                Return CType(Me("TitleRatingsSavedStartTime"),Date)
            End Get
            Set
                Me("TitleRatingsSavedStartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property OverallSavedEndTime() As Date
            Get
                Return CType(Me("OverallSavedEndTime"),Date)
            End Get
            Set
                Me("OverallSavedEndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NameBasicsSavedEndTime() As Date
            Get
                Return CType(Me("NameBasicsSavedEndTime"),Date)
            End Get
            Set
                Me("NameBasicsSavedEndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleAkasSavedEndTime() As Date
            Get
                Return CType(Me("TitleAkasSavedEndTime"),Date)
            End Get
            Set
                Me("TitleAkasSavedEndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleBasicsSavedEndTime() As Date
            Get
                Return CType(Me("TitleBasicsSavedEndTime"),Date)
            End Get
            Set
                Me("TitleBasicsSavedEndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleCrewSavedEndTime() As Date
            Get
                Return CType(Me("TitleCrewSavedEndTime"),Date)
            End Get
            Set
                Me("TitleCrewSavedEndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleEpisodeSavedEndTime() As Date
            Get
                Return CType(Me("TitleEpisodeSavedEndTime"),Date)
            End Get
            Set
                Me("TitleEpisodeSavedEndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitlePrincipalsSavedEndTime() As Date
            Get
                Return CType(Me("TitlePrincipalsSavedEndTime"),Date)
            End Get
            Set
                Me("TitlePrincipalsSavedEndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TitleRatingsSavedEndTime() As Date
            Get
                Return CType(Me("TitleRatingsSavedEndTime"),Date)
            End Get
            Set
                Me("TitleRatingsSavedEndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15427319")>  _
        Public Property NameBasicsSavedRowCount() As Long
            Get
                Return CType(Me("NameBasicsSavedRowCount"),Long)
            End Get
            Set
                Me("NameBasicsSavedRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("57452364")>  _
        Public Property TitleAkasSavedRowCount() As Long
            Get
                Return CType(Me("TitleAkasSavedRowCount"),Long)
            End Get
            Set
                Me("TitleAkasSavedRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12541389")>  _
        Public Property TitleBasicsSavedRowCount() As Long
            Get
                Return CType(Me("TitleBasicsSavedRowCount"),Long)
            End Get
            Set
                Me("TitleBasicsSavedRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12541389")>  _
        Public Property TitleCrewSavedRowCount() As Long
            Get
                Return CType(Me("TitleCrewSavedRowCount"),Long)
            End Get
            Set
                Me("TitleCrewSavedRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9687178")>  _
        Public Property TitleEpisodeSavedRowCount() As Long
            Get
                Return CType(Me("TitleEpisodeSavedRowCount"),Long)
            End Get
            Set
                Me("TitleEpisodeSavedRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("99764730")>  _
        Public Property TitlePrincipalsSavedRowCount() As Long
            Get
                Return CType(Me("TitlePrincipalsSavedRowCount"),Long)
            End Get
            Set
                Me("TitlePrincipalsSavedRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1683289")>  _
        Public Property TitleRatingsSavedRowCount() As Long
            Get
                Return CType(Me("TitleRatingsSavedRowCount"),Long)
            End Get
            Set
                Me("TitleRatingsSavedRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("209653830")>  _
        Public Property OverallSavedRowCount() As Long
            Get
                Return CType(Me("OverallSavedRowCount"),Long)
            End Get
            Set
                Me("OverallSavedRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15380979")>  _
        Public Property SavedRowCount401() As Long
            Get
                Return CType(Me("SavedRowCount401"),Long)
            End Get
            Set
                Me("SavedRowCount401") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("47")>  _
        Public Property SavedRowCount402() As Long
            Get
                Return CType(Me("SavedRowCount402"),Long)
            End Get
            Set
                Me("SavedRowCount402") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property SavedRowCount403() As Long
            Get
                Return CType(Me("SavedRowCount403"),Long)
            End Get
            Set
                Me("SavedRowCount403") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("17114040")>  _
        Public Property SavedRowCount404() As Long
            Get
                Return CType(Me("SavedRowCount404"),Long)
            End Get
            Set
                Me("SavedRowCount404") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("28")>  _
        Public Property SavedRowCount405() As Long
            Get
                Return CType(Me("SavedRowCount405"),Long)
            End Get
            Set
                Me("SavedRowCount405") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11")>  _
        Public Property SavedRowCount406() As Long
            Get
                Return CType(Me("SavedRowCount406"),Long)
            End Get
            Set
                Me("SavedRowCount406") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12541389")>  _
        Public Property SavedRowCount407() As Long
            Get
                Return CType(Me("SavedRowCount407"),Long)
            End Get
            Set
                Me("SavedRowCount407") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SavedRowCount408() As Long
            Get
                Return CType(Me("SavedRowCount408"),Long)
            End Get
            Set
                Me("SavedRowCount408") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("35")>  _
        Public Property SavedRowCount409() As Long
            Get
                Return CType(Me("SavedRowCount409"),Long)
            End Get
            Set
                Me("SavedRowCount409") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("19644165")>  _
        Public Property SavedRowCount410() As Long
            Get
                Return CType(Me("SavedRowCount410"),Long)
            End Get
            Set
                Me("SavedRowCount410") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("57452364")>  _
        Public Property SavedRowCount411() As Long
            Get
                Return CType(Me("SavedRowCount411"),Long)
            End Get
            Set
                Me("SavedRowCount411") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("163")>  _
        Public Property SavedRowCount412() As Long
            Get
                Return CType(Me("SavedRowCount412"),Long)
            End Get
            Set
                Me("SavedRowCount412") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("311606")>  _
        Public Property SavedRowCount413() As Long
            Get
                Return CType(Me("SavedRowCount413"),Long)
            End Get
            Set
                Me("SavedRowCount413") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property SavedRowCount414() As Long
            Get
                Return CType(Me("SavedRowCount414"),Long)
            End Get
            Set
                Me("SavedRowCount414") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("314710")>  _
        Public Property SavedRowCount415() As Long
            Get
                Return CType(Me("SavedRowCount415"),Long)
            End Get
            Set
                Me("SavedRowCount415") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SavedRowCount416() As Long
            Get
                Return CType(Me("SavedRowCount416"),Long)
            End Get
            Set
                Me("SavedRowCount416") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1666")>  _
        Public Property SavedRowCount417() As Long
            Get
                Return CType(Me("SavedRowCount417"),Long)
            End Get
            Set
                Me("SavedRowCount417") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("99764730")>  _
        Public Property SavedRowCount418() As Long
            Get
                Return CType(Me("SavedRowCount418"),Long)
            End Get
            Set
                Me("SavedRowCount418") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10642136")>  _
        Public Property SavedRowCount419() As Long
            Get
                Return CType(Me("SavedRowCount419"),Long)
            End Get
            Set
                Me("SavedRowCount419") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("48687272")>  _
        Public Property SavedRowCount420() As Long
            Get
                Return CType(Me("SavedRowCount420"),Long)
            End Get
            Set
                Me("SavedRowCount420") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3401367")>  _
        Public Property SavedRowCount421() As Long
            Get
                Return CType(Me("SavedRowCount421"),Long)
            End Get
            Set
                Me("SavedRowCount421") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SavedRowCount422() As Long
            Get
                Return CType(Me("SavedRowCount422"),Long)
            End Get
            Set
                Me("SavedRowCount422") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("19")>  _
        Public Property SavedRowCount423() As Long
            Get
                Return CType(Me("SavedRowCount423"),Long)
            End Get
            Set
                Me("SavedRowCount423") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3401367")>  _
        Public Property SavedRowCount424() As Long
            Get
                Return CType(Me("SavedRowCount424"),Long)
            End Get
            Set
                Me("SavedRowCount424") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9687178")>  _
        Public Property SavedRowCount425() As Long
            Get
                Return CType(Me("SavedRowCount425"),Long)
            End Get
            Set
                Me("SavedRowCount425") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1676404")>  _
        Public Property SavedRowCount426() As Long
            Get
                Return CType(Me("SavedRowCount426"),Long)
            End Get
            Set
                Me("SavedRowCount426") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15454479")>  _
        Public Property SavedCountPrincipals() As Long
            Get
                Return CType(Me("SavedCountPrincipals"),Long)
            End Get
            Set
                Me("SavedCountPrincipals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("49")>  _
        Public Property SavedCountProfessions() As Long
            Get
                Return CType(Me("SavedCountProfessions"),Long)
            End Get
            Set
                Me("SavedCountProfessions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("48942647")>  _
        Public Property SavedCountTitleCharacters() As Long
            Get
                Return CType(Me("SavedCountTitleCharacters"),Long)
            End Get
            Set
                Me("SavedCountTitleCharacters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("19644165")>  _
        Public Property SavedCountTitleGenres() As Long
            Get
                Return CType(Me("SavedCountTitleGenres"),Long)
            End Get
            Set
                Me("SavedCountTitleGenres") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("630492")>  _
        Public Property SavedCountTitleNameAttributes() As Long
            Get
                Return CType(Me("SavedCountTitleNameAttributes"),Long)
            End Get
            Set
                Me("SavedCountTitleNameAttributes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("58185048")>  _
        Public Property SavedCountTitleNames() As Long
            Get
                Return CType(Me("SavedCountTitleNames"),Long)
            End Get
            Set
                Me("SavedCountTitleNames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("103668658")>  _
        Public Property SavedCountTitlePrincipals() As Long
            Get
                Return CType(Me("SavedCountTitlePrincipals"),Long)
            End Get
            Set
                Me("SavedCountTitlePrincipals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12611790")>  _
        Public Property SavedCountTitles() As Long
            Get
                Return CType(Me("SavedCountTitles"),Long)
            End Get
            Set
                Me("SavedCountTitles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property SavedCountTitleTypes() As Long
            Get
                Return CType(Me("SavedCountTitleTypes"),Long)
            End Get
            Set
                Me("SavedCountTitleTypes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("169")>  _
        Public Property SavedCountAttributes() As Long
            Get
                Return CType(Me("SavedCountAttributes"),Long)
            End Get
            Set
                Me("SavedCountAttributes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9743260")>  _
        Public Property SavedCountEpisodes() As Long
            Get
                Return CType(Me("SavedCountEpisodes"),Long)
            End Get
            Set
                Me("SavedCountEpisodes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("28")>  _
        Public Property SavedCountGenres() As Long
            Get
                Return CType(Me("SavedCountGenres"),Long)
            End Get
            Set
                Me("SavedCountGenres") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("17185592")>  _
        Public Property SavedCountPrimaryProfessions() As Long
            Get
                Return CType(Me("SavedCountPrimaryProfessions"),Long)
            End Get
            Set
                Me("SavedCountPrimaryProfessions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40")>  _
        Public Property TimeOut401() As Integer
            Get
                Return CType(Me("TimeOut401"),Integer)
            End Get
            Set
                Me("TimeOut401") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("46")>  _
        Public Property TimeOut402() As Integer
            Get
                Return CType(Me("TimeOut402"),Integer)
            End Get
            Set
                Me("TimeOut402") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeOut403() As Integer
            Get
                Return CType(Me("TimeOut403"),Integer)
            End Get
            Set
                Me("TimeOut403") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("106")>  _
        Public Property TimeOut404() As Integer
            Get
                Return CType(Me("TimeOut404"),Integer)
            End Get
            Set
                Me("TimeOut404") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeOut405() As Integer
            Get
                Return CType(Me("TimeOut405"),Integer)
            End Get
            Set
                Me("TimeOut405") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeOut406() As Integer
            Get
                Return CType(Me("TimeOut406"),Integer)
            End Get
            Set
                Me("TimeOut406") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("74")>  _
        Public Property TimeOut407() As Integer
            Get
                Return CType(Me("TimeOut407"),Integer)
            End Get
            Set
                Me("TimeOut407") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeOut408() As Integer
            Get
                Return CType(Me("TimeOut408"),Integer)
            End Get
            Set
                Me("TimeOut408") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("112")>  _
        Public Property TimeOut409() As Integer
            Get
                Return CType(Me("TimeOut409"),Integer)
            End Get
            Set
                Me("TimeOut409") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("96")>  _
        Public Property TimeOut410() As Integer
            Get
                Return CType(Me("TimeOut410"),Integer)
            End Get
            Set
                Me("TimeOut410") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("814")>  _
        Public Property TimeOut411() As Integer
            Get
                Return CType(Me("TimeOut411"),Integer)
            End Get
            Set
                Me("TimeOut411") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeOut412() As Integer
            Get
                Return CType(Me("TimeOut412"),Integer)
            End Get
            Set
                Me("TimeOut412") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property TimeOut413() As Integer
            Get
                Return CType(Me("TimeOut413"),Integer)
            End Get
            Set
                Me("TimeOut413") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeOut414() As Integer
            Get
                Return CType(Me("TimeOut414"),Integer)
            End Get
            Set
                Me("TimeOut414") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("52")>  _
        Public Property TimeOut415() As Integer
            Get
                Return CType(Me("TimeOut415"),Integer)
            End Get
            Set
                Me("TimeOut415") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("232")>  _
        Public Property TimeOut416() As Integer
            Get
                Return CType(Me("TimeOut416"),Integer)
            End Get
            Set
                Me("TimeOut416") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192")>  _
        Public Property TimeOut417() As Integer
            Get
                Return CType(Me("TimeOut417"),Integer)
            End Get
            Set
                Me("TimeOut417") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("844")>  _
        Public Property TimeOut418() As Integer
            Get
                Return CType(Me("TimeOut418"),Integer)
            End Get
            Set
                Me("TimeOut418") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("270")>  _
        Public Property TimeOut419() As Integer
            Get
                Return CType(Me("TimeOut419"),Integer)
            End Get
            Set
                Me("TimeOut419") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
        Public Property TimeOut420() As Integer
            Get
                Return CType(Me("TimeOut420"),Integer)
            End Get
            Set
                Me("TimeOut420") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property TimeOut421() As Integer
            Get
                Return CType(Me("TimeOut421"),Integer)
            End Get
            Set
                Me("TimeOut421") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeOut422() As Integer
            Get
                Return CType(Me("TimeOut422"),Integer)
            End Get
            Set
                Me("TimeOut422") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeOut423() As Integer
            Get
                Return CType(Me("TimeOut423"),Integer)
            End Get
            Set
                Me("TimeOut423") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property TimeOut424() As Integer
            Get
                Return CType(Me("TimeOut424"),Integer)
            End Get
            Set
                Me("TimeOut424") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
        Public Property TimeOut425() As Integer
            Get
                Return CType(Me("TimeOut425"),Integer)
            End Get
            Set
                Me("TimeOut425") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property TimeOut426() As Integer
            Get
                Return CType(Me("TimeOut426"),Integer)
            End Get
            Set
                Me("TimeOut426") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.ImportAndAddRawImdbData.My.MySettings
            Get
                Return Global.ImportAndAddRawImdbData.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
